### ISSUE TITLE
working installation

### ISSUE THREAD

**Issue by bluegenes** [ngs-docs/2023-snakemake-book-draft#14]
On 04/04/2023, I did a fresh install with the following approach:

I wrote the following `environment.yml`:
```
name: 2023-snakemake-book-draft
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - rust>=1.67,<2
  - snakemake>=7.25,<8
  - sourmash-minimal>=4.6.1,<5
```
Create and activate this environment: 
```
mamba env create -f environment.yml
mamba activate 2023-snakemake-book-draft
```

To install `mdbook-admonish` in this env, I ran:
```
cargo install mdbook-admonish
``` 

Then, as directed, I added the following line to my `~/.zshrc` to add the cargo bin to my path:
```
export PATH="$PATH:Users/ntward/.cargo/bin"
```

Then I ran `make test` to verify the install was working.

**Comment by ctb** [comment]
I think I updated things correctly in #15, and CI is now working in #17. 🎉  thanks!
